import React from "react";
import { Link } from "react-router-dom";
import errorImage from "../../assets/errorImage.svg"
import FooterIcon from "../../components/Icons/FooterIcon.js";
import {
  Col,
  Row, Button, ButtonGroup
} from "reactstrap";
import Widget from "../../components/Widget/Widget.js";
import s from "../error/ErrorPage.module.scss";

const PrivacyPage = () => {
  return (
          <div>
      <Row>
        <Col className="mb-4" xs={12}>
          <Widget className="widget-p-lg">
            <Row>
              <Col xs={12} sm={12} xl={12} className="mb-5 mb-sm-0">
			  <div className={s.footer}>
				<Link to="/template/dashboard">
				<Button>
					Back To Home
				</Button>
				</Link>
			  </div>
			    <p className="headline-1 mb-4 text-muted">Disclaimer</p> 
                  <p className="body-3 text-muted mb-0">1. Copatent is a platform designed for structural preparation of your patent applications using this website’s tools and AI prompts. Although, we created this platform for your entertainment and educational purposes, it can be extremely useful for SMEs and entrepreneurs.</p>
				  <p className="body-3 text-muted mb-0">2. While we strive to ensure that all content posted on our website is accurate and up-to-date, we cannot guarantee the completeness or reliability of any information or content provided by other users.</p>
				  <p className="body-3 text-muted mb-0">3. The prompts and responses on our platform are generated by large language models, which are trained on third-party datasets and may contain biases or errors. As such, we cannot be held responsible for any consequences that may arise from the use of Copatent generated. We advise users to exercise caution and independently verify any information before acting on it. Especially we advise to rely on lawyers and IP attorneys advise during your journey of patenting.</p>
				  <p className="body-3 text-muted mb-0">4. By using our website, you agree to hold Copatent and its affiliates harmless from any claims, damages, or losses arising from your use of our website.</p>
				  <p className="body-3 text-muted mb-0">5. Your information is safe with us as we are not collecting or analyzing any of your data. Copatent is not responsible for human-to-human interactions. We urge all users to be respectful and polite to each other. While Copatent strives to make your human-to-AI interactions as smooth as possible, please note that the generative AI models used by us are operated by third-party entities, and such interactions are covered by their respective terms of use.</p>
				  <p className="body-3 text-muted mb-0">6. Please note that your work will become be visible to other users if you choose to share it.</p>
				  <p className="body-3 text-muted mb-0">7. This is an early version of our terms of use, which may be updated by Copatent in the future without notice.</p>
				  <p className="body-3 text-muted mb-0">Thanks for using Copatent.</p>
				<div className={s.footer}>
				<ButtonGroup >
				<Link to="/terms">
				<Button>
					Terms and Condition
				</Button>
				</Link>
				<Link to="/privacy">
				<Button>
					Privacy Policy
				</Button>
				</Link>
				<Link to="/disclaimer">
				<Button>
					Disclaimer
				</Button>
				</Link>
				</ButtonGroup>
                </div>
			  </Col>
			</Row>
		  </Widget>
		</Col>
	  </Row>
	  </div>

  );
}

export default PrivacyPage;
